// <auto-generated />
using System;
using Helpdesk.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Helpdesk.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191208000232_incidentes")]
    partial class incidentes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("Helpdesk.API.model.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.HasKey("Id");

                    b.ToTable("Applcations");
                });

            modelBuilder.Entity("Helpdesk.API.Model.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ApplicationId");

                    b.Property<int>("Decription");

                    b.Property<DateTime?>("createDate");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("Helpdesk.API.Model.Incident", b =>
                {
                    b.HasOne("Helpdesk.API.model.Application", "Application")
                        .WithMany("Incidents")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
